### ISSUE TITLE
Frontend updaten a.d.h.v. nieuwe gateway filter parameters

### ISSUE THREAD

**Issue by lencodes** [Klantinteractie-Servicesysteem/.github#11]
- [x] Boolean en integer filters updaten;
- [x] Embedded filters toevoegen;
- [x] Globale filters (_limit, _page, _order, "x-commongateway-metadata) omschrijven.

**Comment by lencodes** [comment]
Laatste loodjes planning 19-12

- [ ] - [ ] bij query_suggestion wordt nu vanuit de frontend een contenttype text meegegeven, dat moet json zijn. 
- [ ] Put moet omgebouwd naar PATCH. Ma refinen met Lennart
- [ ] Wildcard zoeken ombouwen van %% naar [like]

**Comment by sytskevanhasselt** [comment]
Getest in diverse eerdere rondes. Is klaar.
