### ISSUE TITLE
Taak: Openpub Wordpress plugin updaten op de development omgeving

### ISSUE THREAD

**Issue by lencodes** [Klantinteractie-Servicesysteem/.github#14]
Momenteel draait de development Wordpress omgeving nog op de oude Openpub plugin en communiceert die daardoor nog _niet_ met de gateway. Deze mag geüpdatet worden.

**Comment by lencodes** [comment]
Update is gedaan, de Wordpress omgeving communiceert nu met de Gateway a.d.h.v. de geüpdatete plugin. Alles lijkt te werken zoals verwacht in deze communicatie.

Let op: de schemas zijn geüpdatet, waardoor het formulier op de gateway ui weer groter is geworden (voorheen enkel de `name` property), hier gaan we naar kijken.

**Comment by lencodes** [comment]
Update: simplificatie van de schemas is in de KISS-BUNDLE geüpdatet.

**Comment by lencodes** [comment]
> Klopt het dat er hiermee Skills vervallen zijn in Wordpress? Ik zie nl een aantal 'onbekend' skills in de lijst nieuws en werkinstructies.

Ja, wanneer een skill in Wordpress bestond, maar is verwijderd uit de gateway, dan wordt die ook verwijderd uit Wordpress en wordt er "Onbekend" getoond. Wanneer in Wordpress het bericht wordt geüpdatet, zal die 'm verwijderen en zal "Onbekend" ook vervallen.

**Comment by sytskevanhasselt** [comment]
Is getest, gedaan en ok
