### ISSUE TITLE
Niet correcte links in readme.md

### ISSUE THREAD

**Issue by MarcoKlerks** [Klantinteractie-Servicesysteem/.github#61]
Zie: https://github.com/Klantinteractie-Servicesysteem/.github/tree/main/profile

De volgende links lijken niet te kloppen / niet te werken:
- "de gemeente Utrecht en Dimpact" (bovenaan)
- "ZGW Zaken" (bij de API's)
- "ZGW Catalogi" (bij de API's)
- "ZGW Documenten" (bij de API's)

**Comment by sytskevanhasselt** [comment]
Dank voor de oplettendheid! Dat gaan we aanpassen.

**Comment by sytskevanhasselt** [comment]
We hebben de links aangepast en bijgewerkt.
